apiVersion: v1
name: gjw-project
version: 0.1.0
kubeVersion: v1.13.10-r1-CCE2.0.28.B001
maintainers:
  - name: liuwg-a
    email: liuwg-a@glodon.com
    url: https://github.com/Jacksonary
engine: gotpl
appVersion: "1.0"
deprecated: false
tillerVersion: 2.12.2