---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploy.app }}
  labels:
    service-cluster: {{ .Values.deploy.serviceCluster }}
    app: {{ .Values.deploy.app }}
    project-type: java
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.service.port }}
    name: http
  selector:
    service-cluster: {{ .Values.deploy.serviceCluster }}
    app: {{ .Values.deploy.app }}
    project-type: java