{{- if (or .Values.filebeat .Values.log.extraVolumeMounts) }}
apiVersion: v1
kind: Secret
metadata:
  name: filebeat
  labels:
    app: filebeat
type: Opaque
data:
  filebeat.yml: {{ toYaml .Values.filebeat.config | indent 4 | b64enc }}
{{- end }}
