{{- if .Values.service.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.deploy.app }}
{{- if .Values.service.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.service.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
  labels:
    service-cluster: {{ .Values.deploy.serviceCluster }}
    app: {{ .Values.deploy.app }}
    project-type: java
spec:
  rules:
  {{- range .Values.service.ingress.serpaths }}
  - host: {{ .hosts }}
    http:
      paths:
      {{- range .extraPath }}
        - path: {{ .path }}
          backend:
            serviceName: {{ .serviceName }}
            servicePort: {{ .servicePort }}
      {{- end }}
  {{- end }}
{{- if .Values.service.ingress.tls }}
  tls:
  {{- range .Values.service.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
{{- end }}
